  
<script>

export default {
  name: 'Card'
}
</script>
  

<template>



<div class="product">
  <div class="disappear">
    <img src="../assets/img/1.webp" alt="Relaxed Tee" title="Relaxed Tee" class="img">
    <img src="../assets/img/1b.webp" alt="Relaxed TeeB" title="Relaxed TeeB" class="imgb">
    <div class="disappearheart">
      <span class="heart"> &hearts; </span>
      <span class="rheart"> &hearts; </span>
    </div>
    <span class="discount"> -50% </span>
    <span class="eco">Sostenibilità</span>
  </div>
  
  
  <span class="brand">Levi's</span>
  <h3 class="item"> RELAXED FIT TEE UNISEX</h3>
  <span class="price"> 14,99 &euro;</span>
  <span class="old-price"> 29,99 &euro;</span>
</div>

</template>


<style>

</style>